<!DOCTYPE html>
<html lang"fr">
<head>
    <meta charset="utf-8" />
   
    <title>blog</title>
    
</head>
<body>
                <form method="post" action="addUsers.php">
        <p>
                <label for= "name">nom</label>
                <input type="text" name="name" id"name" placeholder=" entrez votre nom">

        </p>
         <p>
                <label for= "surname">prenom</label>
                <input type="text" name="surname" id"surname" placeholder=" entrez votre prenom">
        </p>
        <p>
                <label for="e mail">e mail</label>
                <input type="text" name="e mail" id="mail" placeholder=" entrez votre e mail ">
       
        </p> 
        <p>
                <label for="mot de passe"> entrez mot de passe</label>
                <input type="text" name="mot de passe" id="mot de passe" placeholder=" entrez le mot de passe ">
        </p> 
       
        <p>
                <label for="mot de passe">comfirmer votre mot de passe</label>
                <input type="text" name="mot de passe" id="mot de passe" placeholder=" comfirmer le mot de passe ">
        </p>
        <p>
                <label for="bio">bio</label>
                <input type="text" name="bio" id="bio" placeholder=" entrez votre bio">
        </p>
        <p>
                <label for="avatar"></label>
                <input type="text" name="avatar" id="avatar" placeholder=" entrez votre avatar">
        </p>
         <p>
                <label for="nom d'utilisateur">nom d'utilisateur</label>
                <input type="text" name="user name" id="user name" placeholder="entrez le nom d'utilisateur">
        </p>
        <P>
                <input type="submit"value="s'incrire" </button>
        </P>
</form>
</body>
</htm